sudo: required
services:
- docker
deploy:
  provider: gae
  keyfile: gotham-254312-cd30ddd476eb.json
  project: gotham-254312
script:
- docker-compose build
before_install:
- openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in gotham-254312-cd30ddd476eb.json.enc -out gotham-254312-cd30ddd476eb.json -d
