sudo: required
services:
  - docker

deploy:
  provider: heroku
  api_key:
    secure: "5a46fd74-c69b-4d23-9767-369b1fa482ec"
  app: gotham-time-manager

# after_deploy: 
#   - "cd server && mix ecto.setup && mix phx.server&"
#   - "cd client && npm run serve"

script:
  - docker-compose build