apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: gotham-project
spec:
  containers:
  - name: frontend
    image: gcr.io/gotham-254312/frontend:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
    readinessProbe:
      httpGet:
        path: /
        port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: gotham-project
---
apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels:
    app: gotham-project
spec:
  containers:
  - name: backend
    image: gcr.io/gotham-254312/backend:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 4000
    readinessProbe:
      httpGet:
        path: /api
        port: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP
  selector:
    app: gotham-project
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gotham-project
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/issuer: "letsencrypt-prod"
    certmanager.k8s.io/acme-challenge-type: http01

spec:
  tls:
  - hosts:
    - gotham-254312.appspot.com
    secretName: default-token-8662q
  rules:
  - host: gotham-254312.appspot.com
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80
      - path: /api
        backend:
          serviceName: backend
          servicePort: 4000