apiVersion: apps/v1
kind: Deployment
metadata:
  name: gothamweb
  labels:
    app: gotham
spec:
  selector:
    matchLabels:
      app: gotham
      tier: web
  template:
    metadata:
      labels:
        app: gotham
        tier: web
    spec:
      containers:
      - name: frontend
        image: gcr.io/gotham-254312/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
      - name: backend
        image: gcr.io/gotham-254312/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        readinessProbe:
          httpGet:
            path: /api
            port: 4000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gothamweb
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/issuer: "letsencrypt-prod"
    certmanager.k8s.io/acme-challenge-type: http01
    kubernetes.io/ingress.global-static-ip-name: gothamweb-ip
spec:
  tls:
  - hosts:
    - 35.244.240.5
    secretName: default-token-8662q
  rules:
  - host: 35.244.240.5
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80
      - path: /api
        backend:
          serviceName: backend
          servicePort: 4000